#!/bin/sh
ifexec() {
	local prg="$1"; shift
	which "$prg" > /dev/null 2>&1 && "$prg" $*
}

[ -r ~/.fehbg ] && sh ~/.fehbg &

ifexec unclutter -root -noevents &
ifexec numlockx &
ifexec xbindkeys
ifexec urxvtd -q -o -f
ifexec dex -a
exec i3
