set guioptions-=m
set guioptions-=l
set guioptions-=L
set guioptions-=r
set guioptions-=b
set guioptions-=T
set guioptions+=c

set guifont=Ioveska:h14,Inconsolata:h14,Menlo\ Regular:h11,Source\ Code\ Pro\ Medium:h11
