#!/usr/bin/env bash
set -e

abspath() {
	local path="$1";

	if [[ -d $path ]]; then
		(cd "$path"; pwd -P)
	else
		echo "$path"
	fi
}

inst() {
	src="$1"; shift;
	dst="$1"; shift;
	[ -d "$(dirname $dst)" ] || mkdir -p "$(dirname $dst)"
	[ -e "$dst" ] || ln -s "$src" "$dst"
}

SRC="$(abspath $(dirname $(dirname $0)))"
DST="$HOME"

[ ! -d "$DST/.config" ] && mkdir -p "$DST/.config"

inst "$SRC/inputrc" "$DST/.inputrc"
inst "$SRC/k9s/skin.yml" "$DST/.k9s/skin.yml"
inst "$SRC/kitty" "$DST/.config/kitty"
inst "$SRC/starship.toml" "$DST/.config/starship.toml"
inst "$SRC/tmux.conf" "$DST/.tmux.conf"

### Linux only
if [ "$OSTYPE" == "linux-gnu" ]; then
	[ ! -d "$DST/.config/share" ] && mkdir -p "$DST/.config/share"

	inst "$SRC/autostart" "$DST/.config/autostart"
	inst "$SRC/fontconfig" "$DST/.config/fontconfig"
	inst "$SRC/i3" "$DST/.config/i3"
	inst "$SRC/icons" "$DST/.icons"
	inst "$SRC/mpd" "$DST/.config/mpd"
	inst "$SRC/polybar" "$DST/.config/polybar"
	inst "$SRC/rofi" "$DST/.config/rofi"
	inst "$SRC/xbindkeysrc" "$DST/.xbindkeysrc"

	# Fonts
	if [ ! -e "$DST/.fonts/iosevka" ]; then
		mkdir -p "$DST/.fonts"
		version="26.2.2"

		iosevka_zip=$(mktemp /tmp/ioveska.XXXXXX.zip)
		curl -sLo "$iosevka_zip" "https://github.com/be5invis/Iosevka/releases/download/v26.2.2/ttf-iosevka-${version}.zip"
		unzip "$iosevka_zip" -d "$DST/.fonts/iosevka"
		rm $iosevka_zip

		for variant in term fixed; do
			iosevka_zip=$(mktemp /tmp/ioveska.XXXXXX.zip)
			curl -sLo "$iosevka_zip" "https://github.com/be5invis/Iosevka/releases/download/v26.2.2/ttf-iosevka-${variant}-${version}.zip"
			unzip "$iosevka_zip" -d "$DST/.fonts/iosevka"
			rm $iosevka_zip
		done

		fc-cache -f "$DST/.fonts/iosevka"
	fi
fi

