#!/bin/bash
set -e

abspath() {
	local path="$1";

	if [[ -d $path ]]; then
		(cd "$path"; pwd -P)
	else
		echo "$path"
	fi
}

inst() {
	src="$1"; shift;
	dst="$1"; shift;
	[ -d "$(dirname $dst)" ] || mkdir -p "$(dirname $dst)"
	[ -e "$dst" ] || ln -s "$src" "$dst"
}

SRC="$(abspath $(dirname $(dirname $0)))"
DST="$HOME"

[ ! -d "$DST/.config" ] && mkdir -p "$DST/.config"

inst "$SRC/bash" "$DST/.bash"
inst "$SRC/bashrc" "$DST/.bashrc"
inst "$SRC/fish" "$DST/.config/fish"
inst "$SRC/gitconfig" "$DST/.gitconfig"
inst "$SRC/gitignore" "$DST/.gitignore"
inst "$SRC/inputrc" "$DST/.inputrc"
inst "$SRC/tmux.conf" "$DST/.tmux.conf"
inst "$SRC/vim" "$DST/.config/nvim"
inst "$SRC/tmux.conf" "$DST/.tmux.conf"
inst "$SRC/alacritty/alacritty.yml" "$DST/.config/alacritty/alacritty.yml"
inst "$SRC/starship.toml" "$DST/.config/starship.toml"

### Linux only
if [ "$OSTYPE" == "linux-gnu" ]; then
	[ ! -d "$DST/.config/share" ] && mkdir -p "$DST/.config/share"

	inst "$SRC/Xdefaults" "$DST/.Xdefaults"
	inst "$SRC/autostart" "$DST/.config/autostart"
	inst "$SRC/compton.conf" "$DST/.config/compton.conf"
	inst "$SRC/fontconfig" "$DST/.config/fontconfig"
	inst "$SRC/i3" "$DST/.config/i3"
	inst "$SRC/icons" "$DST/.icons"
	inst "$SRC/mpd" "$DST/.config/mpd"
	inst "$SRC/polybar" "$DST/.config/polybar"
	inst "$SRC/rofi" "$DST/.config/rofi"
	inst "$SRC/xbindkeysrc" "$DST/.xbindkeysrc"
	inst "$SRC/xprofile" "$DST/.xprofile"

	# Fonts
	if [ ! -e "$DST/.fonts/iosevka" ]; then
		ioveska_zip=$(mktemp /tmp/ioveska.XXXXXX.zip)
		curl -sLo $ioveska_zip "https://github.com/be5invis/Iosevka/releases/download/v1.14.3/01-iosevka-1.14.3.zip"
		unzip $ioveska_zip -d "$DST/.fonts/iosevka"
		rm $ioveska_zip
	fi
fi

