#!/bin/bash
if [[ $(uname -s) = "Darwin" ]]; then
	alias ls='ls -G'
else
	alias ls='ls --color=auto'
fi

gvim --version | grep '+clientserver' >/dev/null && alias gvim='gvim --remote'
vim --version  | grep '+clientserver' >/dev/null && alias vim='vim --remote'
