#!/bin/bash
if [[ $(uname -s) = "Darwin" ]]; then
	alias ls='ls -G'
else
	alias ls='ls --color=auto'
fi

type -f exa >/dev/null 2>&1 && alias ls='exa'

if [[ "$TERM" = "xterm-kitty" ]]; then
    alias ssh='kitty +kitten ssh'
fi
