#!/bin/bash
export HISTCONTROL=ignoreboth:erasedups

export TERMINAL="urxvtc"
export EDITOR=vim
export ALTERNATE_EDITOR=vi
which nvim > /dev/null && 2>&1 && export EDITOR=nvim

export PATH="$PATH:$HOME/.cabal/bin"

# Use the keychain SSH agent if it's available
which keychain > /dev/null 2>&1 && eval $(keychain --eval --quiet)

which rg > /dev/null 2>&1
if [ $? ]; then
	export FZF_DEFAULT_COMMAND='rg --files --hidden --follow --glob "!.git/*"'
fi
