#!/bin/bash
export PATH="$HOME/.local/bin:$PATH"

export HISTCONTROL=ignoreboth:erasedups

export TERMINAL="urxvtc"
export EDITOR=vim
export ALTERNATE_EDITOR=vi
which nvim > /dev/null 2>&1 && export EDITOR=nvim

# Use the keychain SSH agent if it's available
which keychain > /dev/null 2>&1 && eval $(keychain --eval --quiet)

[ -f /opt/asdf-vm/asdf.sh ] && source /opt/asdf-vm/asdf.sh
[ -f /usr/share/fzf/key-bindings.bash ] && source /usr/share/fzf/key-bindings.bash

which direnv > /dev/null 2>&1 && eval "$(direnv hook bash)"

which rg > /dev/null 2>&1 && export FZF_DEFAULT_COMMAND='rg --files --hidden --follow --glob "!.git/*"'
