#!/bin/bash
_gitbranch() {
	type -t __git_ps1 >/dev/null && __git_ps1 "$*"
}

SEP=""
PS1=""
PS1="$PS1\[\e[100;30m\] \u@\h \[\e[42;90m\]${SEP}"
PS1="$PS1\[\e[42;30m\] \w \[\e[0;32m\]${SEP}"
PS1="$PS1\$(_gitbranch '  %s')"
PS1="$PS1\[\e[0m\]\n>>= "
